package:
  name: ucsc_tools
  version: "357"

build:
  number: 1

requirements:
  run:
    - ucsc-bedgraphtobigwig ==357
    - ucsc-bedtobigbed ==357
    - ucsc-fatotwobit ==357
    - ucsc-liftover ==357
    - ucsc-nibfrag ==357
    - ucsc-twobittofa ==357
    - ucsc-wigtobigwig ==357

test:
  commands:
    - which bedGraphToBigWig
    - which bedToBigBed
    - which faToTwoBit
    - which liftOver
    - which nibFrag
    - which twoBitToFa
    - which wigToBigWig

about:
  home: "http://hgdownload.cse.ucsc.edu/admin/exe/"
  license: "varies; see http://genome.ucsc.edu/license"
  summary: "Subset of UCSC tools required by tools and converters distributed with Galaxy"
